# Generated by Django 5.0.3 on 2024-05-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='userId',
            field=models.TextField(blank=True),
        ),
    ]
