# Generated by Django 5.0.3 on 2024-05-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_signup_password_alter_signup_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
